import "./globals.css";
import { Inter } from "next/font/google";
import Image from "next/image";

import NavBar from "@/components/NavBar";
import Hero from "@/components/Hero";
import LogoBox from "@/components/LogoBox";
import DescBox from "@/components/DescBox";
import OfferingBox from "@/components/OfferingBox";
import ImageBox from "@/components/ImageBox";
import Testimonial from "@/components/Testimonial";
import Footer from "@/components/Footer";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar />
        <div className="home"/>
        <Hero/>
        <LogoBox />
        
        <DescBox
        id={"about"}
          headingOne={"ABOUT US"}
          headingTwo={"We Always<br/>Prioritize Quality<br/>And Unique Style"}
          desc={
            "Goba is an agency with 10+ years of experience<br/>that has helped more than 300+ projects from<br/>small to large projects. We also have several<br/>projects that can help your business"
          }
          button={"Contact Us"}
        />
        <Image
          className="placeholder_image"
          src="/place_holder.png"
          alt="placeholder"
          width={1000}
          height={1000}
          priority
        />
        <DescBox
         id={"service"}
          headingOne={"SERVICE"}
          headingTwo={
            "Provide The Best<br/>Offer According To<br/>Your Needs<br/>"
          }
          desc={
            "We can adjust your needs so that your<br/>business can grow and you can run <br/>other businesses"
          }
          button={"More Project"}
        />
        <section className="offering_layout">
          <OfferingBox
            num={"01"}
            headingOne={"UIUX Design"}
            desc={
              "Make your business more attractive by building brand awareness, we<br/>have several services such as logo design, brand identity, packaging,<br/>and also everything related to brand."
            }
          />
          <OfferingBox
            num={"02"}
            headingOne={"Branding"}
            desc={
              "Make your business more attractive by building brand awareness, we<br/>have several services such as logo design, brand identity, packaging,<br/>and also everything related to brand."
            }
          />
          <OfferingBox
            num={"03"}
            headingOne={"Social Media"}
            desc={
              "Make your business more attractive by building brand awareness, we<br/>have several services such as logo design, brand identity, packaging,<br/>and also everything related to brand."
            }
          />
          <OfferingBox
            num={"04"}
            headingOne={"Digital Marketing"}
            desc={
              "Make your business more attractive by building brand awareness, we<br/>have several services such as logo design, brand identity, packaging,<br/>and also everything related to brand."
            }
          />
        </section>
        <DescBox
         id={"project"}
          headingOne={"SERVICE"}
          headingTwo={"Some of The<br/>Projects We Have <br/>As Well<br/>"}
          desc={
            "We can adjust your needs so that your<br/>business can grow and you can run<br/>other businesses"
          }
          button={"More Project"}
        />
        <ImageBox />
        <section className="centre">
          <Testimonial />
        </section>
        <Footer />
      </body>
    </html>
  );
}
